import Head from "next/head";
//import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import DebugHome from "./home/index";
import { GetServerSideProps, GetStaticProps } from "next";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import supabase from "@/utils/supabase";

const Home = (props:any) => {
	
	return (
		<>
			<Head>
				<title>Auto Flow</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DebugHome projects={props.Projects}/>
			{/* <Router>
					<div>
						<Routes>
							<Route path="/" element={} />
						</Routes>
					</div>
			</Router> */}
		</>
	);
}

export default Home


 export const getServerSideProps: GetServerSideProps = async (context) => {
	const supabase = createServerSupabaseClient(context);
	const { data: { session }, } = await supabase.auth.getSession()
	if (!session)
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false,
      },
    }
	const { data:Projects, error } = await supabase
			  .from("project")
			  .select('*')
			  .eq('userId',session.user.id)
			  .order('created_at', {ascending:false})
			 //console.log(Projects, error)
	return {
	  props: { session,Projects },
	};
  };